# version: '3.4'
# services:
#   web:
#     build: .
#     ports:
#     - "2100:4200"
version: "3"
services:
 web:
   build: .
   labels:
     - "SERVICE_4200_NAME=chat-ui-service"
     - "SERVICE_TAG=chat-ui-serviceTag"
