sudo: required
addons:
chrome: stable
language: node_js
node_js:
- "8"
notifications:
email:
  on_success: always
  on_failure: always
slack: srboeingdotnet:UIU3Bl3s8QViLrC2yS7GV9NI
mono: none
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular-devkit/build-angular
- npm install -g @angular/cli
- npm install

script:
- chmod +x ./deploy.sh
- ng build
- ng test --watch=false

after_success:
- /bin/bash ./deploy.sh
